### ISSUE TITLE
Kész a beadandó

### ISSUE THREAD

**Issue by KGabor5** [Teaching-projects/januari-beadando-KGabor5#1]
Jó napot kívánok!
Elkészültem a beadandóval.
Teszteltem is.

**Comment by hegyhati** [comment]
Rendben van, 5, en mondjuk az elet akasztofas kiirasat is kitettem volna fuggvenybe.

**Comment by KGabor5** [comment]
Köszönöm! Legközelebb akkor figyelni fogok az ilyenre is.
